// Code generated by protoc-gen-go. DO NOT EDIT.
// source: acknowledge.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HeartBeatAck struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatAck) Reset()         { *m = HeartBeatAck{} }
func (m *HeartBeatAck) String() string { return proto.CompactTextString(m) }
func (*HeartBeatAck) ProtoMessage()    {}
func (*HeartBeatAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc5054c71bb07194, []int{0}
}

func (m *HeartBeatAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatAck.Unmarshal(m, b)
}
func (m *HeartBeatAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatAck.Marshal(b, m, deterministic)
}
func (m *HeartBeatAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatAck.Merge(m, src)
}
func (m *HeartBeatAck) XXX_Size() int {
	return xxx_messageInfo_HeartBeatAck.Size(m)
}
func (m *HeartBeatAck) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatAck.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatAck proto.InternalMessageInfo

// 错误信息回复
type ErrAck struct {
	AckName              *string  `protobuf:"bytes,1,req,name=AckName" json:"AckName,omitempty"`
	Err                  *string  `protobuf:"bytes,2,req,name=Err" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrAck) Reset()         { *m = ErrAck{} }
func (m *ErrAck) String() string { return proto.CompactTextString(m) }
func (*ErrAck) ProtoMessage()    {}
func (*ErrAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc5054c71bb07194, []int{1}
}

func (m *ErrAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrAck.Unmarshal(m, b)
}
func (m *ErrAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrAck.Marshal(b, m, deterministic)
}
func (m *ErrAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrAck.Merge(m, src)
}
func (m *ErrAck) XXX_Size() int {
	return xxx_messageInfo_ErrAck.Size(m)
}
func (m *ErrAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrAck.DiscardUnknown(m)
}

var xxx_messageInfo_ErrAck proto.InternalMessageInfo

func (m *ErrAck) GetAckName() string {
	if m != nil && m.AckName != nil {
		return *m.AckName
	}
	return ""
}

func (m *ErrAck) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

// 聊天数据回复
type ChatAck struct {
	Data                 *string  `protobuf:"bytes,1,req,name=Data" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatAck) Reset()         { *m = ChatAck{} }
func (m *ChatAck) String() string { return proto.CompactTextString(m) }
func (*ChatAck) ProtoMessage()    {}
func (*ChatAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc5054c71bb07194, []int{2}
}

func (m *ChatAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatAck.Unmarshal(m, b)
}
func (m *ChatAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatAck.Marshal(b, m, deterministic)
}
func (m *ChatAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatAck.Merge(m, src)
}
func (m *ChatAck) XXX_Size() int {
	return xxx_messageInfo_ChatAck.Size(m)
}
func (m *ChatAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatAck.DiscardUnknown(m)
}

var xxx_messageInfo_ChatAck proto.InternalMessageInfo

func (m *ChatAck) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

// 创建房间
type CreateRoomAck struct {
	RoomId               *string  `protobuf:"bytes,1,req,name=RoomId" json:"RoomId,omitempty"`
	Num                  *int32   `protobuf:"varint,2,req,name=Num" json:"Num,omitempty"`
	Result               *bool    `protobuf:"varint,3,req,name=Result" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomAck) Reset()         { *m = CreateRoomAck{} }
func (m *CreateRoomAck) String() string { return proto.CompactTextString(m) }
func (*CreateRoomAck) ProtoMessage()    {}
func (*CreateRoomAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc5054c71bb07194, []int{3}
}

func (m *CreateRoomAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomAck.Unmarshal(m, b)
}
func (m *CreateRoomAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomAck.Marshal(b, m, deterministic)
}
func (m *CreateRoomAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomAck.Merge(m, src)
}
func (m *CreateRoomAck) XXX_Size() int {
	return xxx_messageInfo_CreateRoomAck.Size(m)
}
func (m *CreateRoomAck) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomAck.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomAck proto.InternalMessageInfo

func (m *CreateRoomAck) GetRoomId() string {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return ""
}

func (m *CreateRoomAck) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *CreateRoomAck) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

// 离开房间
type LeaveRoomAck struct {
	RoomId               *string  `protobuf:"bytes,1,req,name=RoomId" json:"RoomId,omitempty"`
	Num                  *int32   `protobuf:"varint,2,req,name=Num" json:"Num,omitempty"`
	Result               *bool    `protobuf:"varint,3,req,name=Result" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoomAck) Reset()         { *m = LeaveRoomAck{} }
func (m *LeaveRoomAck) String() string { return proto.CompactTextString(m) }
func (*LeaveRoomAck) ProtoMessage()    {}
func (*LeaveRoomAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc5054c71bb07194, []int{4}
}

func (m *LeaveRoomAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoomAck.Unmarshal(m, b)
}
func (m *LeaveRoomAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoomAck.Marshal(b, m, deterministic)
}
func (m *LeaveRoomAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoomAck.Merge(m, src)
}
func (m *LeaveRoomAck) XXX_Size() int {
	return xxx_messageInfo_LeaveRoomAck.Size(m)
}
func (m *LeaveRoomAck) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoomAck.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoomAck proto.InternalMessageInfo

func (m *LeaveRoomAck) GetRoomId() string {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return ""
}

func (m *LeaveRoomAck) GetNum() int32 {
	if m != nil && m.Num != nil {
		return *m.Num
	}
	return 0
}

func (m *LeaveRoomAck) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

// 进入房间
type EnterRoomAck struct {
	RoomId               *string  `protobuf:"bytes,1,req,name=RoomId" json:"RoomId,omitempty"`
	RoomName             *string  `protobuf:"bytes,2,req,name=RoomName" json:"RoomName,omitempty"`
	Result               *bool    `protobuf:"varint,3,req,name=Result" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterRoomAck) Reset()         { *m = EnterRoomAck{} }
func (m *EnterRoomAck) String() string { return proto.CompactTextString(m) }
func (*EnterRoomAck) ProtoMessage()    {}
func (*EnterRoomAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc5054c71bb07194, []int{5}
}

func (m *EnterRoomAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterRoomAck.Unmarshal(m, b)
}
func (m *EnterRoomAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterRoomAck.Marshal(b, m, deterministic)
}
func (m *EnterRoomAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterRoomAck.Merge(m, src)
}
func (m *EnterRoomAck) XXX_Size() int {
	return xxx_messageInfo_EnterRoomAck.Size(m)
}
func (m *EnterRoomAck) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterRoomAck.DiscardUnknown(m)
}

var xxx_messageInfo_EnterRoomAck proto.InternalMessageInfo

func (m *EnterRoomAck) GetRoomId() string {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return ""
}

func (m *EnterRoomAck) GetRoomName() string {
	if m != nil && m.RoomName != nil {
		return *m.RoomName
	}
	return ""
}

func (m *EnterRoomAck) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*HeartBeatAck)(nil), "protocol.HeartBeatAck")
	proto.RegisterType((*ErrAck)(nil), "protocol.ErrAck")
	proto.RegisterType((*ChatAck)(nil), "protocol.ChatAck")
	proto.RegisterType((*CreateRoomAck)(nil), "protocol.CreateRoomAck")
	proto.RegisterType((*LeaveRoomAck)(nil), "protocol.LeaveRoomAck")
	proto.RegisterType((*EnterRoomAck)(nil), "protocol.EnterRoomAck")
}

func init() { proto.RegisterFile("acknowledge.proto", fileDescriptor_dc5054c71bb07194) }

var fileDescriptor_dc5054c71bb07194 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x90, 0x31, 0x4b, 0xc6, 0x30,
	0x10, 0x86, 0xb1, 0xd5, 0xb6, 0x1e, 0x55, 0x34, 0x83, 0x04, 0x41, 0x28, 0x99, 0x3a, 0x39, 0xf9,
	0x07, 0x6a, 0x2d, 0x28, 0x48, 0xd1, 0x8c, 0x6e, 0x47, 0x7a, 0x28, 0xa4, 0x6d, 0xe4, 0x4c, 0xf5,
	0xef, 0x4b, 0x62, 0x74, 0x93, 0x6f, 0xf9, 0xa6, 0x3c, 0x6f, 0x78, 0xef, 0x19, 0x5e, 0x38, 0x47,
	0x63, 0x57, 0xf7, 0x35, 0xd3, 0xf4, 0x4a, 0xd7, 0xef, 0xec, 0xbc, 0x13, 0x55, 0x7c, 0x8c, 0x9b,
	0xd5, 0x29, 0xd4, 0xf7, 0x84, 0xec, 0x6f, 0x09, 0x7d, 0x67, 0xac, 0xba, 0x81, 0x62, 0x60, 0xee,
	0x8c, 0x15, 0x12, 0xca, 0xce, 0xd8, 0x11, 0x17, 0x92, 0x07, 0x4d, 0xd6, 0x1e, 0xeb, 0xdf, 0x28,
	0xce, 0x20, 0x1f, 0x98, 0x65, 0x16, 0x7f, 0x03, 0xaa, 0x2b, 0x28, 0xfb, 0xb7, 0x28, 0x10, 0x02,
	0x0e, 0xef, 0xd0, 0x63, 0xba, 0x89, 0xac, 0x9e, 0xe1, 0xa4, 0x67, 0x42, 0x4f, 0xda, 0xb9, 0x25,
	0x94, 0x2e, 0xa0, 0x08, 0xf8, 0x30, 0xa5, 0x5a, 0x4a, 0xc1, 0x3c, 0x6e, 0x4b, 0x34, 0x1f, 0xe9,
	0x80, 0xb1, 0x49, 0x1f, 0xdb, 0xec, 0x65, 0xde, 0x64, 0x6d, 0xa5, 0x53, 0x52, 0x4f, 0x50, 0x3f,
	0x12, 0x7e, 0xee, 0xd1, 0xf8, 0x02, 0xf5, 0xb0, 0x7a, 0xe2, 0x5d, 0xc6, 0x4b, 0xa8, 0x02, 0xc5,
	0x61, 0x7e, 0x26, 0xf8, 0xcb, 0xff, 0xb9, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xe5, 0xd6,
	0x3e, 0x83, 0x01, 0x00, 0x00,
}
