// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cst.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//创建房间
type CreateRoomCst struct {
	PlayerId             *string  `protobuf:"bytes,1,req,name=PlayerId" json:"PlayerId,omitempty"`
	RoomName             *string  `protobuf:"bytes,2,req,name=RoomName" json:"RoomName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomCst) Reset()         { *m = CreateRoomCst{} }
func (m *CreateRoomCst) String() string { return proto.CompactTextString(m) }
func (*CreateRoomCst) ProtoMessage()    {}
func (*CreateRoomCst) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ab54014d815c68, []int{0}
}

func (m *CreateRoomCst) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomCst.Unmarshal(m, b)
}
func (m *CreateRoomCst) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomCst.Marshal(b, m, deterministic)
}
func (m *CreateRoomCst) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomCst.Merge(m, src)
}
func (m *CreateRoomCst) XXX_Size() int {
	return xxx_messageInfo_CreateRoomCst.Size(m)
}
func (m *CreateRoomCst) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomCst.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomCst proto.InternalMessageInfo

func (m *CreateRoomCst) GetPlayerId() string {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return ""
}

func (m *CreateRoomCst) GetRoomName() string {
	if m != nil && m.RoomName != nil {
		return *m.RoomName
	}
	return ""
}

//进入房间
type EnterRoomCst struct {
	PlayerId             *string  `protobuf:"bytes,1,req,name=PlayerId" json:"PlayerId,omitempty"`
	RoomName             *string  `protobuf:"bytes,2,req,name=RoomName" json:"RoomName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterRoomCst) Reset()         { *m = EnterRoomCst{} }
func (m *EnterRoomCst) String() string { return proto.CompactTextString(m) }
func (*EnterRoomCst) ProtoMessage()    {}
func (*EnterRoomCst) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ab54014d815c68, []int{1}
}

func (m *EnterRoomCst) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterRoomCst.Unmarshal(m, b)
}
func (m *EnterRoomCst) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterRoomCst.Marshal(b, m, deterministic)
}
func (m *EnterRoomCst) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterRoomCst.Merge(m, src)
}
func (m *EnterRoomCst) XXX_Size() int {
	return xxx_messageInfo_EnterRoomCst.Size(m)
}
func (m *EnterRoomCst) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterRoomCst.DiscardUnknown(m)
}

var xxx_messageInfo_EnterRoomCst proto.InternalMessageInfo

func (m *EnterRoomCst) GetPlayerId() string {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return ""
}

func (m *EnterRoomCst) GetRoomName() string {
	if m != nil && m.RoomName != nil {
		return *m.RoomName
	}
	return ""
}

//进入房间,cst回复
type EnterRoomCstResponse struct {
	PlayerId             *string  `protobuf:"bytes,1,req,name=PlayerId" json:"PlayerId,omitempty"`
	RoomName             *string  `protobuf:"bytes,2,req,name=RoomName" json:"RoomName,omitempty"`
	Result               *bool    `protobuf:"varint,3,req,name=Result" json:"Result,omitempty"`
	RoomId               *string  `protobuf:"bytes,4,req,name=RoomId" json:"RoomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterRoomCstResponse) Reset()         { *m = EnterRoomCstResponse{} }
func (m *EnterRoomCstResponse) String() string { return proto.CompactTextString(m) }
func (*EnterRoomCstResponse) ProtoMessage()    {}
func (*EnterRoomCstResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ab54014d815c68, []int{2}
}

func (m *EnterRoomCstResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterRoomCstResponse.Unmarshal(m, b)
}
func (m *EnterRoomCstResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterRoomCstResponse.Marshal(b, m, deterministic)
}
func (m *EnterRoomCstResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterRoomCstResponse.Merge(m, src)
}
func (m *EnterRoomCstResponse) XXX_Size() int {
	return xxx_messageInfo_EnterRoomCstResponse.Size(m)
}
func (m *EnterRoomCstResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterRoomCstResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnterRoomCstResponse proto.InternalMessageInfo

func (m *EnterRoomCstResponse) GetPlayerId() string {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return ""
}

func (m *EnterRoomCstResponse) GetRoomName() string {
	if m != nil && m.RoomName != nil {
		return *m.RoomName
	}
	return ""
}

func (m *EnterRoomCstResponse) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

func (m *EnterRoomCstResponse) GetRoomId() string {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return ""
}

//离开房间
type LeaveRoomCst struct {
	PlayerId             *string  `protobuf:"bytes,1,req,name=PlayerId" json:"PlayerId,omitempty"`
	RoomName             *string  `protobuf:"bytes,2,req,name=RoomName" json:"RoomName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoomCst) Reset()         { *m = LeaveRoomCst{} }
func (m *LeaveRoomCst) String() string { return proto.CompactTextString(m) }
func (*LeaveRoomCst) ProtoMessage()    {}
func (*LeaveRoomCst) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ab54014d815c68, []int{3}
}

func (m *LeaveRoomCst) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoomCst.Unmarshal(m, b)
}
func (m *LeaveRoomCst) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoomCst.Marshal(b, m, deterministic)
}
func (m *LeaveRoomCst) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoomCst.Merge(m, src)
}
func (m *LeaveRoomCst) XXX_Size() int {
	return xxx_messageInfo_LeaveRoomCst.Size(m)
}
func (m *LeaveRoomCst) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoomCst.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoomCst proto.InternalMessageInfo

func (m *LeaveRoomCst) GetPlayerId() string {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return ""
}

func (m *LeaveRoomCst) GetRoomName() string {
	if m != nil && m.RoomName != nil {
		return *m.RoomName
	}
	return ""
}

//离开房间,cst回复
type LeaveRoomCstResponse struct {
	PlayerId             *string  `protobuf:"bytes,1,req,name=PlayerId" json:"PlayerId,omitempty"`
	RoomName             *string  `protobuf:"bytes,2,req,name=RoomName" json:"RoomName,omitempty"`
	Result               *bool    `protobuf:"varint,3,req,name=Result" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRoomCstResponse) Reset()         { *m = LeaveRoomCstResponse{} }
func (m *LeaveRoomCstResponse) String() string { return proto.CompactTextString(m) }
func (*LeaveRoomCstResponse) ProtoMessage()    {}
func (*LeaveRoomCstResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ab54014d815c68, []int{4}
}

func (m *LeaveRoomCstResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRoomCstResponse.Unmarshal(m, b)
}
func (m *LeaveRoomCstResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRoomCstResponse.Marshal(b, m, deterministic)
}
func (m *LeaveRoomCstResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRoomCstResponse.Merge(m, src)
}
func (m *LeaveRoomCstResponse) XXX_Size() int {
	return xxx_messageInfo_LeaveRoomCstResponse.Size(m)
}
func (m *LeaveRoomCstResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRoomCstResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRoomCstResponse proto.InternalMessageInfo

func (m *LeaveRoomCstResponse) GetPlayerId() string {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return ""
}

func (m *LeaveRoomCstResponse) GetRoomName() string {
	if m != nil && m.RoomName != nil {
		return *m.RoomName
	}
	return ""
}

func (m *LeaveRoomCstResponse) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

//聊天请求
type ChatCst struct {
	RoomName             *string  `protobuf:"bytes,1,req,name=RoomName" json:"RoomName,omitempty"`
	Data                 *string  `protobuf:"bytes,2,req,name=Data" json:"Data,omitempty"`
	PlayerId             *string  `protobuf:"bytes,3,req,name=PlayerId" json:"PlayerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatCst) Reset()         { *m = ChatCst{} }
func (m *ChatCst) String() string { return proto.CompactTextString(m) }
func (*ChatCst) ProtoMessage()    {}
func (*ChatCst) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ab54014d815c68, []int{5}
}

func (m *ChatCst) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatCst.Unmarshal(m, b)
}
func (m *ChatCst) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatCst.Marshal(b, m, deterministic)
}
func (m *ChatCst) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatCst.Merge(m, src)
}
func (m *ChatCst) XXX_Size() int {
	return xxx_messageInfo_ChatCst.Size(m)
}
func (m *ChatCst) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatCst.DiscardUnknown(m)
}

var xxx_messageInfo_ChatCst proto.InternalMessageInfo

func (m *ChatCst) GetRoomName() string {
	if m != nil && m.RoomName != nil {
		return *m.RoomName
	}
	return ""
}

func (m *ChatCst) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

func (m *ChatCst) GetPlayerId() string {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return ""
}

//聊天请求，cst回复
type ChatCstResponse struct {
	PlayerId             *string  `protobuf:"bytes,1,req,name=PlayerId" json:"PlayerId,omitempty"`
	Result               *bool    `protobuf:"varint,2,req,name=Result" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatCstResponse) Reset()         { *m = ChatCstResponse{} }
func (m *ChatCstResponse) String() string { return proto.CompactTextString(m) }
func (*ChatCstResponse) ProtoMessage()    {}
func (*ChatCstResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8ab54014d815c68, []int{6}
}

func (m *ChatCstResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatCstResponse.Unmarshal(m, b)
}
func (m *ChatCstResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatCstResponse.Marshal(b, m, deterministic)
}
func (m *ChatCstResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatCstResponse.Merge(m, src)
}
func (m *ChatCstResponse) XXX_Size() int {
	return xxx_messageInfo_ChatCstResponse.Size(m)
}
func (m *ChatCstResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatCstResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChatCstResponse proto.InternalMessageInfo

func (m *ChatCstResponse) GetPlayerId() string {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return ""
}

func (m *ChatCstResponse) GetResult() bool {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*CreateRoomCst)(nil), "protocol.CreateRoomCst")
	proto.RegisterType((*EnterRoomCst)(nil), "protocol.EnterRoomCst")
	proto.RegisterType((*EnterRoomCstResponse)(nil), "protocol.EnterRoomCstResponse")
	proto.RegisterType((*LeaveRoomCst)(nil), "protocol.LeaveRoomCst")
	proto.RegisterType((*LeaveRoomCstResponse)(nil), "protocol.LeaveRoomCstResponse")
	proto.RegisterType((*ChatCst)(nil), "protocol.ChatCst")
	proto.RegisterType((*ChatCstResponse)(nil), "protocol.ChatCstResponse")
}

func init() { proto.RegisterFile("cst.proto", fileDescriptor_b8ab54014d815c68) }

var fileDescriptor_b8ab54014d815c68 = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2e, 0x2e, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0xee, 0x5c, 0xbc,
	0xce, 0x45, 0xa9, 0x89, 0x25, 0xa9, 0x41, 0xf9, 0xf9, 0xb9, 0xce, 0xc5, 0x25, 0x42, 0x52, 0x5c,
	0x1c, 0x01, 0x39, 0x89, 0x95, 0xa9, 0x45, 0x9e, 0x29, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x9c, 0x41,
	0x70, 0x3e, 0x48, 0x0e, 0xa4, 0xcc, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x09, 0x22, 0x07, 0xe3, 0x2b,
	0xb9, 0x71, 0xf1, 0xb8, 0xe6, 0x95, 0xa4, 0x16, 0x51, 0x6a, 0x4e, 0x1d, 0x97, 0x08, 0xb2, 0x39,
	0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0xe4, 0x9a, 0x27, 0x24, 0xc6, 0xc5, 0x16, 0x94,
	0x5a, 0x5c, 0x9a, 0x53, 0x22, 0xc1, 0xac, 0xc0, 0xa4, 0xc1, 0x11, 0x04, 0xe5, 0x81, 0xc5, 0xf3,
	0xf3, 0x73, 0x3d, 0x53, 0x24, 0x58, 0xc0, 0x3a, 0xa0, 0x3c, 0x90, 0x3f, 0x7c, 0x52, 0x13, 0xcb,
	0x28, 0x0e, 0x8f, 0x34, 0x2e, 0x11, 0x64, 0x73, 0x68, 0xe5, 0x0f, 0xa5, 0x50, 0x2e, 0x76, 0xe7,
	0x8c, 0xc4, 0x12, 0xa8, 0x53, 0xe1, 0xda, 0x19, 0xd1, 0xb4, 0x0b, 0x71, 0xb1, 0xb8, 0x24, 0x96,
	0x24, 0x42, 0x8d, 0x05, 0xb3, 0x51, 0x9c, 0xc2, 0x8c, 0xea, 0x14, 0x25, 0x57, 0x2e, 0x7e, 0xa8,
	0xb1, 0x44, 0xb9, 0x1c, 0xe1, 0x3a, 0x26, 0x64, 0xd7, 0x01, 0x02, 0x00, 0x00, 0xff, 0xff, 0x9a,
	0x41, 0x11, 0xdc, 0x74, 0x02, 0x00, 0x00,
}
